// Exporting an object containing mongoDB models
module.exports = {
	Analog: require("./Analog"),
	Blocks: require("./Blocks"),
	Entries: require("./Entries"),
	Fields: require("./Fields"),
	FieldGroups: require("./FieldGroups"),
	Forms: require("./Forms"),
	FieldValues: require("./FieldValues"),
	Links: require("./Links"),
	Media: require("./Media"),
	Menus: require("./Menus"),
	Meta: require("./Meta"),
	PagesNotFound: require("./PagesNotFound"),
	Pages: require("./Pages"),
	Permalinks: require("./Permalinks"),
	Recaptcha: require("./Recaptcha"),
	Redirects: require("./Redirects"),
	RepeaterFields: require("./RepeaterFields"),
	Smtp: require("./Smtp"),
	Taxonomies: require("./Taxonomies"),
	Terms: require("./Terms"),
	Tokens: require("./Tokens"),
	Users: require("./Users")
}